### ISSUE TITLE
Stubfence error during CodeShip build

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [raix/stubfence#1]
Hi, Since I installed `ground:db` package, I got this error when Codeship install all my packages and try to run a build:

`Error: Arg! Meteor just broke raix:stubfence! Please report to @raix at github, and he will work his butt off trying to fix this`

**Comment by caio-ribeiro-pereira** [comment]
@raix any ideas about how to solve this issue? thanks!

**Comment by raix** [comment]
why did I ever put an error message like that in the code... It could be something to do with load order? the ddp package should be loaded before this package (since it depends on ddp)

Try running meteor with the `--production` flag

**Comment by caio-ribeiro-pereira** [comment]
Hi! I did what you said and the problem still the same, this was the command: 

``` bash
meteor --test --once --production --settings=settings.json
```

and this was the entire error:

``` bash
W20150527-14:41:37.314(0)? (STDERR) 
W20150527-14:41:37.315(0)? (STDERR) /home/rof/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150527-14:41:37.315(0)? (STDERR) 						throw(ex);
W20150527-14:41:37.316(0)? (STDERR) 						      ^
W20150527-14:41:37.316(0)? (STDERR) Error: Arg! Meteor just broke raix:stubfence! Please report to @raix at github, and he will work his butt off trying to fix this
W20150527-14:41:37.316(0)? (STDERR)     at inFence (raix:stubfence/util.js:4:1)
W20150527-14:41:37.316(0)? (STDERR)     at /home/rof/src/bitbucket.org/99folks-team/app-99folks/.meteor/local/build/programs/server/packages/raix_stubfence.js:27:4
W20150527-14:41:37.316(0)? (STDERR)     at /home/rof/src/bitbucket.org/99folks-team/app-99folks/.meteor/local/build/programs/server/packages/raix_stubfence.js:124:3
W20150527-14:41:37.316(0)? (STDERR)     at /home/rof/src/bitbucket.org/99folks-team/app-99folks/.meteor/local/build/programs/server/boot.js:222:10
W20150527-14:41:37.316(0)? (STDERR)     at Array.forEach (native)
W20150527-14:41:37.316(0)? (STDERR)     at Function._.each._.forEach (/home/rof/meteor/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150527-14:41:37.317(0)? (STDERR)     at /home/rof/src/bitbucket.org/99folks-team/app-99folks/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by caio-ribeiro-pereira** [comment]
Hi again, I really sorry to ask again, but I need any help or solution to help my CI works fine again. If I knew how to fix it, I would send a pull request.

@raix, do you know another solution to fix this issue?

Thanks!

**Comment by raix** [comment]
@caio-ribeiro-pereira the error is at https://github.com/raix/stubfence/blob/master/util.js#L1

Maybe try changing it to:
```js
_DDP = Package['ddp'].LivedataTest || Package['ddp-client'].LivedataTest;
```

**Comment by raix** [comment]
or add the `ddp-client` to the dependency list

**Comment by caio-ribeiro-pereira** [comment]
@raix it didn't work both tips, is there a way to disable this lib when be running `meteor --test`?

**Comment by caio-ribeiro-pereira** [comment]
I solved the issue! In Codeship I was installing always the latest meteor version from github `devel` branch, and I changed to the branch `release-1.1` which is the production used today, and the `stubfence` works. Anyway thanks for your help!
